### ISSUE TITLE
ModBus TCP Register XLS File. Register 2903 Incorrect Value received

### ISSUE THREAD

**Issue by optio50** [victronenergy/dbus_modbustcp#13]
Register 2903. /Settings/Cgwacs/BatteryLife/SocLimit
The Remarks in the XLS file say "Same as the displayed value in the GUI when BatteryLife is used"
This does not seem to be the case.
Mine says 60% in the GUI yet ModbusCLI returns 500. Expected value is 600 ( /10 )

Cerbo-GX Firmware 2.90~14

I can easily deal with this situation but just want to know if its correct.

Thanks

**Comment by izak** [comment]
That remark is unnecessarily vague. In the GUI it displays the minimum SOC (/Settings/Cgwacs/BatteryLife/MinSocLimit), and then it shows the active SOC limit which is the higher value of the MinSoc and /Settings/Cgwacs/BatteryLife/SocLimit.

So in your case, the GUI likely shows 60% because that is what the MinSoc is set to, while the modbus register returns the lower value determined by the BatteryLife algorithm. Nothing is wrong here, we just need to document it better.

Thanks for reporting!
